# Generated by Django 5.2.1 on 2025-05-30 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('garagem', '0005_alter_veiculo_ano'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='acessorio',
            options={'verbose_name': 'Acessório', 'verbose_name_plural': 'Acessórios'},
        ),
        migrations.AlterModelOptions(
            name='cor',
            options={'verbose_name': 'Cor', 'verbose_name_plural': 'Cores'},
        ),
    ]
